// Re-export types from Prisma client to simplify imports
export { 
  UserRole,
  RefereeRole,
  StageType, 
  CardType,
  MatchState,
  DisplayState,
  User,
  Tournament,
  Stage,
  Match,
  Alliance,
  AllianceScoring,
  Team,
  TeamAlliance,
  MatchControl,
  MatchTimer,
  MatchError,
  MatchReferee,
  AudienceDisplay,
  Field,
  TeamStats,
  Schedule,
  MatchType // Add MatchType to exports
} from '../../generated/prisma';